### ISSUE TITLE
compatibility with NC 18 needed

### ISSUE THREAD

**Issue by wiswedel** [rullzer/sharelisting#3]
Please make this app compatible with Nextcloud 18, since it's a requirement for https://github.com/nextcloud-gmbh/professional_services/issues/181.
Thanks.

**Comment by rullzer** [comment]
While developing just manually change the version in info.xml and check if it still works and then submit a PR.

**Comment by Gatak** [comment]
Would you mind releasing an updated version to the app store? At least for NC 17? =)
